from dotenv import load_dotenv
import os

load_dotenv()

# FORM LOGIN
USER_LOGIN = os.getenv('USER_LOGIN_EJADE')
PASSWORD_LOGIN = os.getenv('PASSWORD_LOGIN_EJADE')

# URLS
URL_MODULES = os.getenv('URL_MODULES')
URL_INCORPORATION = os.getenv('URL_INCORPORATION')
URL_NAV = os.getenv('URL_LOGIN_EJADE')
URL_TRANSFERENCE_MODULE = os.getenv('URL_TRANSFERENCE_MODULE')
URL_TRANSFERENCE = os.getenv('URL_TRANSFERENCE')
URL_TERM_RESPONSABILITY = os.getenv('URL_TERM_RESPONSABILITY')
